# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('secret_question', models.CharField(max_length=200)),
                ('secret_answer', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='repairer_id',
        ),
        migrations.AddField(
            model_name='repairer',
            name='expertise',
            field=models.ManyToManyField(to='two.Expertise'),
        ),
        migrations.AddField(
            model_name='repairer',
            name='rating',
            field=models.ForeignKey(default=datetime.datetime(2016, 8, 31, 19, 59, 3, 785000, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='two.Rating'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='repairer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.Repairer'),
        ),
        migrations.AddField(
            model_name='userr',
            name='fav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.Favourites'),
        ),
        migrations.AddField(
            model_name='userr',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='two.Rating'),
        ),
    ]
